### ISSUE TITLE
Crash when trying to save with bug net in inventory

### ISSUE THREAD

**Issue by justastranger** [spacechase0/BugNet#2]
```
[16:58:08 ERROR game] System.InvalidOperationException: There was an error generating the XML document. ---> System.InvalidOperationException: The type BugNet.BugNetTool was not expected. Use the XmlInclude or SoapInclude attribute to specify types that are not known statically.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterSaveGame.Write49_Item(String n, String ns, Item o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterSaveGame.Write146_Farmer(String n, String ns, Farmer o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterSaveGame.Write245_SaveGame(String n, String ns, SaveGame o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterSaveGame.Write246_SaveGame(Object o)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSerializerNamespaces namespaces, String encodingStyle, String id)
   at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o)
   at SpaceCore.Overrides.SaveGameSaveEnumeratorPatch.SerializeProxy(XmlSerializer serializer, XmlWriter origWriter, Object obj) in C:\Programming\StardewValley\ModSource\SpaceCore_SDV\Overrides\SaveGame.cs:line 362
   at StardewValley.SaveGame+<getSaveEnumerator>d__90.MoveNext_PatchedBy<spacechase0.SpaceCore>(Object )
   at StardewValley.SaveGame.<>c__DisplayClass88_0.<Save>b__0() in C:\GitlabRunner\builds\Gq5qA5P4\1\ConcernedApe\stardewvalley\Farmer\Farmer\SaveGame.cs:line 386
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
[16:58:08 ERROR SMAPI] An error occurred in the overridden update loop: System.InvalidOperationException: There was an error generating the XML document. ---> System.InvalidOperationException: The type BugNet.BugNetTool was not expected. Use the XmlInclude or SoapInclude attribute to specify types that are not known statically.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterSaveGame.Write49_Item(String n, String ns, Item o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterSaveGame.Write146_Farmer(String n, String ns, Farmer o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterSaveGame.Write245_SaveGame(String n, String ns, SaveGame o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterSaveGame.Write246_SaveGame(Object o)
   --- End of inner exception stack trace ---
   at StardewValley.SaveGame.<Save>d__88.MoveNext() in C:\GitlabRunner\builds\Gq5qA5P4\1\ConcernedApe\stardewvalley\Farmer\Farmer\SaveGame.cs:line 414
   at StardewValley.Menus.SaveGameMenu.update(GameTime time) in C:\GitlabRunner\builds\Gq5qA5P4\1\ConcernedApe\stardewvalley\Farmer\Farmer\Menus\SaveGameMenu.cs:line 123
   at StardewValley.Menus.ShippingMenu.update(GameTime time) in C:\GitlabRunner\builds\Gq5qA5P4\1\ConcernedApe\stardewvalley\Farmer\Farmer\Menus\ShippingMenu.cs:line 340
   at StardewValley.Game1._update(GameTime gameTime) in C:\GitlabRunner\builds\Gq5qA5P4\1\ConcernedApe\stardewvalley\Farmer\Farmer\Game1.cs:line 4080
   at StardewValley.Game1.Update(GameTime gameTime) in C:\GitlabRunner\builds\Gq5qA5P4\1\ConcernedApe\stardewvalley\Farmer\Farmer\Game1.cs:line 3872
   at StardewModdingAPI.Framework.SGame.<>c__DisplayClass40_0.<Update>b__0() in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SGame.cs:line 185
   at StardewModdingAPI.Framework.SCore.OnPlayerInstanceUpdating(SGame instance, GameTime gameTime, Action runUpdate) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SCore.cs:line 692
```

[stardew valley mods list.txt](https://github.com/spacechase0/BugNet/files/6052119/stardew.valley.mods.list.txt)

**Comment by Pathoschild** [comment]
Thanks for the report! That should be fixed in the upcoming Bug Net 1.3.0. If it still happens when you get that version, feel free to post a bug report in the new [spacechase0/StardewValleyMods](https://github.com/spacechase0/StardewValleyMods) repo.
